#!/bin/bash

SCRIPT_NAME=$(basename $0)

usage () {
    echo "
Usage:
  $0 [build|test|install|compact]
  build
    Create documentation, setup venv, and install deps
  test
    Run tests
  install
    Remove all files that are not needed for execution
  compact
    Remove everything that cannot be regenerated by "build"

  NOTE: This script assumes it is being executed in it's directory.
"
}

build () {
    echo "building - building docs"
    cd docsrv
    make github
    cd -
}

test () {
    echo "testing - running unit tests"
    tests/tester.bash
}

# This is weird to my sensibilities, but we install by removing unecessary components the git repo
install () {
    echo "installing - removing the .git directory"
#    rm -rf .git
    rm -rf docs/*
}

compact () {
    echo "compacting - removing the .git directory and venv"
#    if [ -d .git ] ; then
#        rm -rf .git
#    fi
    if [ -d ./docs ] ; then
        rm -rf ./docs/*
    fi
}


if [ $# -ne 1 ] ; then
    usage
    exit 1
fi

if [ ! -f "./$SCRIPT_NAME" ] ; then
    echo "Error: this script must be executed from within the base directory of the application."
    exit
fi

case $1 in
    "build") build; exit 0 ;;
     "test") test; exit 0;;
  "install") install; exit 0;;
  "compact") compact; exit 0;;
          *) echo "Unknown command: $1"; usage; exit 1;;
esac
